version: "3.8"

services:
  postgres:
    image: postgres:16
    container_name: salesbi-postgres
    restart: unless-stopped
    env_file: .env
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "${POSTGRES_PORT}:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./docker/init:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 5s
      timeout: 3s
      retries: 20

  metabase-db:
    image: postgres:16
    container_name: metabase-db
    restart: unless-stopped
    env_file: .env
    environment:
      POSTGRES_DB: ${MB_DB}
      POSTGRES_USER: ${MB_USER}
      POSTGRES_PASSWORD: ${MB_PASSWORD}
    volumes:
      - mbpgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${MB_USER} -d ${MB_DB}"]
      interval: 5s
      timeout: 3s
      retries: 20

  metabase:
    image: metabase/metabase:latest
    container_name: salesbi-metabase
    restart: unless-stopped
    depends_on:
      metabase-db:
        condition: service_healthy
    ports:
      - "3000:3000"

volumes:
  pgdata:
  mbpgdata: