services:
  postgres:
    image: postgres:16
    container_name: salesbi-postgres
    restart: unless-stopped
    env_file: .env
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "${POSTGRES_PORT}:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./docker/init:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 5s
      timeout: 3s
      retries: 20

  metabase-db:
    image: postgres:16
    container_name: metabase-db
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${MB_DB_DBNAME}
      POSTGRES_USER: ${MB_DB_USER}
      POSTGRES_PASSWORD: ${MB_DB_PASS}
    volumes:
      - mbpgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${MB_DB_USER} -d ${MB_DB_DBNAME}"]
      interval: 5s
      timeout: 3s
      retries: 20

  metabase:
    image: metabase/metabase:latest
    container_name: salesbi-metabase
    restart: unless-stopped
    env_file: .env
    ports:
      - "${MB_JETTY_PORT}:3000"
    environment:
      MB_DB_TYPE: ${MB_DB_TYPE}
      MB_DB_DBNAME: ${MB_DB_DBNAME}
      MB_DB_PORT: ${MB_DB_PORT}
      MB_DB_USER: ${MB_DB_USER}
      MB_DB_PASS: ${MB_DB_PASS}
      MB_DB_HOST: ${MB_DB_HOST}
      MB_ENCRYPTION_SECRET: ${MB_ENCRYPTION_SECRET}
    depends_on:
      metabase-db:
        condition: service_healthy
      postgres:
        condition: service_healthy
volumes:
  pgdata:
  mbpgdata:
